spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: FULL
            readTimeout: 5000
            connectTimeout: 2000
#            requestInterceptors: com.example.order.interceptor.TokenInterceptor

